name: XYL Music
favicon: null
layout_spectrum: 0.9892346616834402
typography_spectrum: 0.17245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#606060'
    - '#c8c8c8'
    - '#919191'
  brandStrength: 1
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
